config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index", as: 'root'

  get "/sign_up" => "cadastro#new"
  post "/sign_up/:tipo" => "cadastro#create"

  get "/sign_in" => "sessions#new"
  post "/sign_in" => "sessions#create"

  get "/password" => "passwords#edit"
  patch "/password" => "passwords#update"

  get "/password/reset" => "password_resets#new"
  post "/password/reset" => "password_resets#create"
  get "/password/reset/edit" => "password_resets#edit"
  patch "/password/reset/edit" => "password_resets#update"

  get "/atividade/cadastro" => "cadastro_atividades#new"
  post"/atividade/cadastro" => "cadastro_atividades#create"

  delete "/atividade/:id/deletar" => "atividades#destroy", as: "delete"
  get "/atividade/:id" => "atividades#show", as: "atividade"
  get "/atividade/:id/edit" => "atividades#edit"
  patch "/atividade/:id/edit" => "atividades#update", as: "atividade_edit"

  get "/coordenador/relatorio" => "coordenador#show", as: "coordenador"

  get "/horas" => "horas#show"

  delete "/logout" => "sessions#destroy"

end

app/models/atividade.rb
class Atividade < ApplicationRecord
    belongs_to :professor
    has_many :atividade_aluno, dependent: :destroy
    has_many :alunos, through: :atividade_aluno

    validates :titulo, presence: true
    validates :descricao, presence: true
    validates :modalidade, presence: true
    validates :tipo, presence: true
    validates :alunos, presence: true
    @carga_horaria = 0
    @carga_maxima = 200

    def self.carga_horaria
        @carga_horaria 
    end

    def self.carga_maxima
        @carga_maxima
    end

    def validarAluno?(matricula_aluno, tipo_atividade, modalidade_atividade, modelo)
        aluno = Usuario.find_by(matricula: matricula_aluno).userable
        hora = 0
        hora_maxima = 0
        verificarHoras(aluno)
        case modalidade_atividade
        when "1"
            hora_maxima = aluno.horas_I 
        when "2"
            hora_maxima = aluno.horas_II
        when "3"
            hora_maxima = aluno.horas_III
        when "4"
            hora_maxima = aluno.horas_IV
        end
        if (hora_maxima) <=200
            ativs= AtividadeAluno.joins(:atividade).where(aluno_id: aluno.id ,validada: true, atividades: { tipo: tipo_atividade })
            ativs.each do |ativ|
                hora += Atividade.find(ativ.atividade_id).carga_horaria
            end
        end
        verificarHoras(aluno) 
        hora < modelo.class.carga_maxima && (hora_maxima) <= 200
    end

    def verificarHoras(aluno)
        hora_total=[0,0,0,0]
        ativs= AtividadeAluno.where(aluno_id: aluno.id ,validada: true)
        ativs.each do |ativ|
            hora_total[Atividade.find(ativ.atividade_id).modalidade - 1] += Atividade.find(ativ.atividade_id).carga_horaria
        end
        aluno.update({horas_I: hora_total[0] > 200? 200:hora_total[0],horas_II: hora_total[1] > 200? 200:hora_total[1],horas_III: hora_total[2]> 200? 200:hora_total[2],horas_IV: hora_total[3]> 200? 200:hora_total[3]})
    end

end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
    before_action :require_user_logged_in!
    def show
        @atividade = Atividade.find_by(id: id_param)
    end

    def edit 
        if Current.usuario.userable == Atividade.find_by(id: id_param).professor
            @atividade = Atividade.find_by(id: id_param)
        else
            redirect_to root_path
        end
    end

    def update
        @atividade = Atividade.find_by(id: id_param)
        alunos = []
        alunos_parms[:alunos].each do |aluno|
            alunos.push(Usuario.find_by(matricula:aluno).userable)
        end
        if @atividade.update(atividade_params.merge({alunos: alunos}))
            alunos.each do |aluno|
                x = AtividadeAluno.where(atividade_id: @atividade.id, aluno_id: aluno.id).first
                x.validada = @atividade.validarAluno?(aluno.usuario.matricula,@atividade.tipo,@atividade.modalidade, @atividade)
                x.save
            end
            redirect_to atividade_path(id: @atividade.id)
        else
            render :edit
        end
    end

    def destroy
        @atividade = Atividade.find_by(id: id_param)
        alunos = @atividade.alunos
        if @atividade && Current.usuario.userable == @atividade.professor
            @atividade.destroy
            alunos.each do |aluno|
                Atividade.new.verificarHoras(aluno)
            end
        end
        redirect_to root_path
    end
    

    private
    def id_param
        params.require(:id)
    end

    def atividade_params
        params.require(:atividade).permit(:titulo, :descrição)
    end
    def alunos_parms
        params.require(:atividade).permit(alunos:[])
    end
end

app/helpers/atividades_helper.rb
module AtividadesHelper
    def formatar_modalidade(n)
        modalidade = ["Projetos e Programas","Cursos e Eventos","Prestação de Serviços","Disciplinas Extensionista"]
        modalidade[n-1]
    end
    
    def formatar_tipo(t)
        hash_dados = {
            "colaboracao" => "Participação em projetos de extensão ligados à matriz curricular.",
            "contribuicao" => "Contribuição em projetos isolados cadastrados na PROEX.",
            "coordenacao" => "Organização de eventos educacionais presenciais e remotos.",
            "divulgacao" => "Engajamento em atividades de popularização científica.",
            "participacao" => "Colaboração em comissões de campanhas sociais e programas comunitários.",
            "organizacao" => "Participação em Comissão organizadora de Campanhas ou programas sociais.",
            "formacao" => "Capacitação de professores da rede pública.",
            "auxilio" => "Apoio em aulas de reforço escolar supervisionadas.",
            "orientacao" => "Assessoria e consultoria para públicos-alvo específicos.",
            "interatividade" => "Atendimento ao público em espaços culturais e científicos.",
            "criacao" => "Contribuição na produção de conteúdo sociocultural e científico-tecnológico."
        }
        hash_dados[t] == nil ? t : hash_dados[t]
    end
    def formatar_hora(t)
        hash_dados = {
            "colaboracao" => "/semestre",
            "contribuicao" => "/projeto",
            "coordenacao" => "/curso",
            "divulgacao" => "/dia de evento",
            "participacao" => "/dia de evento",
            "organizacao" => "/dia de evento",
            "formacao" => "/aula",
            "auxilio" => "/aula",
            "orientacao" => "/atividade",
            "interatividade" => "/atividade",
            "criacao" => "/edição"
        }
        hash_dados[t] unless hash_dados[t] == nil
    end
end

app/views/atividades/edit.html.erb
<%=stylesheet_link_tag "atividades"%>
<div id="fundo-tela">
    <div id="fundo-cadastro">
        <%= form_with model: @atividade, url: atividade_edit_path(@atividade.id) do |form| %>
            <h1 id="titulo-login">Editar Atividade</h1>
            <div class="wrapper">
                <hr id="linha-azul">
            </div>
            <div class="wrapper">
                <%=form.text_field :titulo, value: @atividade.titulo, placeholder: "Título", class: "text-input"%>
            </div>
            <div class="wrapper">
                <%=form.text_area :descricao, value: @atividade.descricao, placeholder: "Descrição", class: "text-input"%>
            </div>
            <div class="wrapper">
                <div id="alunos">
                    <% @atividade.alunos.each do |aluno| %>
                        <input class="text-input" value = <%=aluno.usuario.matricula%> multiple="true" type="text" name="atividade[alunos][]" id="atividade_alunos">
                    <%end%> 
                </div>
            </div>
            <div class="wrapper">
            <div class="button-wrapper">
                <button type="button" id="btnAluno">Adicionar Aluno</button>
                <button type="button" id="rmvAluno">Remover Aluno</button>
            </div>
        </div>
        
        <div class="wrapper">
            <%=form.submit "Editar", id: "btnCadastrar"%>
        </div>
        <% end %>
    </div>
</div>
<script>
    const divAlunos = document.querySelector("#alunos")
    const btnRmvAluno = document.querySelector("#rmvAluno")
    const btnAluno = document.querySelector("#btnAluno")
    btnAluno.addEventListener("click",()=>{
        let inputAluno = document.createElement("input")
        inputAluno.name = "atividade[alunos][]"
        inputAluno.id = "atividade_alunos"
        inputAluno.multiple = "true"
        inputAluno.classList.add("text-input")
        inputAluno.placeholder = "Matricula do Aluno"
        divAlunos.appendChild(inputAluno)
        btnRmvAluno.style.display = "block"
    })
    btnRmvAluno.addEventListener("click",()=>{
        if (divAlunos.childElementCount > 1){
            divAlunos.removeChild(divAlunos.lastChild)
            btnRmvAluno.style.display = divAlunos.childElementCount == 1 ? "none":"block"
        }
        })

</script>

app/views/atividades/show.html.erb
<%= render partial: "/public/nav_bar" %>

<h1 id="titulo-home"><%= @atividade.titulo%>
    </div>
<%if Current.usuario.userable_type == "Aluno"%>
<% if AtividadeAluno.where(aluno_id: Current.usuario.userable_id, atividade_id: @atividade.id).first.validada%>
<svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#168821}</style><path  d="M256 48a208 208 0 1 1 0 416 208 208 0 1 1 0-416zm0 464A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-111 111-47-47c-9.4-9.4-24.6-9.4-33.9 0s-9.4 24.6 0 33.9l64 64c9.4 9.4 24.6 9.4 33.9 0L369 209z"/>
<title>Horas validades</title></svg>
<%else%>
<svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#e52207}</style><path d="M256 48a208 208 0 1 1 0 416 208 208 0 1 1 0-416zm0 464A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c-9.4 9.4-9.4 24.6 0 33.9l47 47-47 47c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l47-47 47 47c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-47-47 47-47c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-47 47-47-47c-9.4-9.4-24.6-9.4-33.9 0z"/>
<title>Horas não validades</title></svg>
<%end %>
<%end %>
</h1>

<div style="display: flex; margin-bottom: 25px;">
<h2 id="sub-titulo-atividade"><%= @atividade.professor.usuario.nome %>;</h2>
<% @atividade.alunos.each do |aluno| %>
<h3 class="nome-aluno"><%= aluno.usuario.nome %>;</h3>
<%end%>
</div>
<div class="info">Modalidade: <%= formatar_modalidade(@atividade.modalidade) %></div>
<div class="info">Tipo: <%= formatar_tipo(@atividade.tipo) %></div>
<div class="info">Carga Horaria: <%= @atividade.carga_horaria %>h<%= formatar_hora(@atividade.tipo) %></div>
<div class="atividades-wrapper">
    <p style="font-size: 25px; margin-top: 0;" id="descricao"><%= @atividade.descricao%></p>
</div>
<% if Current.usuario.userable == @atividade.professor %>
<div class="wrapper-buttons">
    <%= link_to "Editar", atividade_edit_path(@atividade.id) , id: "btnEditar"%>
<%= button_to "Excluir", delete_path(@atividade.id), method: :delete ,id: "btnExcluir"%>
</div>
<%end%>
<%= render partial: '/public/footer'%>