config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index", as: 'root'

  get "/sign_up" => "cadastro#new"
  post "/sign_up/:tipo" => "cadastro#create"

  get "/sign_in" => "sessions#new"
  post "/sign_in" => "sessions#create"

  get "/password" => "passwords#edit"
  patch "/password" => "passwords#update"

  get "/password/reset" => "password_resets#new"
  post "/password/reset" => "password_resets#create"
  get "/password/reset/edit" => "password_resets#edit"
  patch "/password/reset/edit" => "password_resets#update"

  get "/atividade/cadastro" => "cadastro_atividades#new"
  post"/atividade/cadastro" => "cadastro_atividades#create"

  delete "/atividade/:id/deletar" => "atividades#destroy", as: "delete"
  get "/atividade/:id" => "atividades#show", as: "atividade"
  get "/atividade/:id/edit" => "atividades#edit"
  patch "/atividade/:id/edit" => "atividades#update", as: "atividade_edit"

  get "/coordenador/relatorio" => "coordenador#show", as: "coordenador"

  get "/horas" => "horas#show"

  delete "/logout" => "sessions#destroy"

end

app/controllers/cadastro_atividades_controller.rb
class CadastroAtividadesController < ApplicationController
    before_action :require_user_logged_in!
    def new
        if Current.usuario.userable_type == "Professor"
            @atividade = Atividade.new
        else
            redirect_to root_path
        end
    end

    def create
        case atividade_params[:tipo]
        when "colaboracao"
           @atividade = Colaboracao.new(atividadeParams.merge({carga_horaria: Colaboracao.carga_horaria}))
            
        when "contribuicao"
            @atividade = Contribuicao.new(atividadeParams.merge({carga_horaria: Contribuicao.carga_horaria}))
            
        when "coordenacao"
            @atividade = Coordenacao.new(atividadeParams.merge({carga_horaria: Coordenacao.carga_horaria}))
            
        when "divulgacao"
            @atividade = Divulgacao.new(atividadeParams.merge({carga_horaria: Divulgacao.carga_horaria}))
            
        when "participacao"
            @atividade = Participacao.new(atividadeParams.merge({carga_horaria: Participacao.carga_horaria}))
            
        when "formacao"
            @atividade = Formacao.new(atividadeParams.merge({carga_horaria: Formacao.carga_horaria}))

        when "auxilio"
            @atividade = Auxilio.new(atividadeParams.merge({carga_horaria: Auxilio.carga_horaria}))

        when "orientacao"
            @atividade = Orientacao.new(atividadeParams.merge({carga_horaria: Orientacao.carga_horaria}))

        when "interatividade"
            @atividade = Interatividade.new(atividadeParams.merge({carga_horaria: Interatividade.carga_horaria}))

        when "criacao"
            @atividade = Criacao.new(atividadeParams.merge({carga_horaria: Criacao.carga_horaria}))

        when "organizacao"
            @atividade = Organizacao.new(atividadeParams.merge({carga_horaria: Organizacao.carga_horaria}))

        else
            @atividade = Atividade.new(atividadeParams)
        end

        Current.usuario.userable.atividades << @atividade

        atividade_params[:alunos].each do |mat|
            aluno = Usuario.find_by(matricula: mat)
            if aluno
                @atividade.alunos << aluno.userable
                @atividade.save
                x = AtividadeAluno.where(atividade_id: @atividade.id, aluno_id: aluno.userable_id).first
                x.validada = @atividade.validarAluno?(aluno.matricula,atividade_params[:tipo],atividade_params[:modalidade], @atividade)
                x.save
                Atividade.new.verificarHoras(aluno.userable)
            end
        end
        if @atividade.save
            redirect_to root_path
        else
            render :new
        end
    end

    private

    def atividade_params
        params.require(:atividade).permit(:titulo, :descricao, :modalidade, :tipo, :carga_horaria, alunos: [])
    end

    def atividadeParams
       ativ = atividade_params
       ativ.delete(:alunos)
       ativ
    end

end

app/views/cadastro_atividades/new.html.erb
<%=stylesheet_link_tag "cadastro_atividades"%>
<div id="fundo-tela">
    <div id="fundo-cadastro">
        <h1 id="titulo-login">Cadastro de Atividade</h1>
        <div class="wrapper">
            <hr id="linha-azul">
        </div>
        <%= form_with model: @atividade, url: atividade_cadastro_path do |form| %>
        <div class="wrapper">
            <%=form.text_field :titulo, placeholder: "Título", class: "text-input"%>
        </div>
        <div class="wrapper">
            <%=form.text_area :descricao, placeholder: "Descrição",class: "text-input"%>
        </div>
        <div class="wrapper">
            <div>
                <select class="text-input" name="atividade[modalidade]" id="atividade_modalidade">
                    <option value="" selected">Modalidade</option>
                    <option value="1">Projetos e Programas</option>
                    <option value="2">Cursos e Eventos</option>
                    <option value="3">Prestação de Serviços</option>
                    <option value="4">Disciplinas Extensionista</option>
                </select>
            </div>
            <div id="abc">
                <select class="text-input" name="atividade[tipo]" id="atividade_tipo">
                    <option value="" selected">Tipo</option>
                </select>
            </div>
        </div>
        <div class="wrapper">
            <div id="alunos">
                <input class="text-input" placeholder="Matricula do Aluno" multiple="true" type="text" name="atividade[alunos][]" id="atividade_alunos"> 
            </div> 
        </div>
        <div class="wrapper">
            <div class="button-wrapper">
                <button type="button" id="btnAluno">Adicionar Aluno</button>
                <button type="button" id="rmvAluno">Remover Aluno</button>
            </div>
        </div>
        
        <div class="wrapper">
            <%=form.submit "Cadastrar", id: "btnCadastrar"%>
        </div>
        <% end %>
    </div>
</div>
<script>
    const selectModalidade = document.querySelector("#atividade_modalidade")
    const btnAluno = document.querySelector("#btnAluno")
    const btnRmvAluno = document.querySelector("#rmvAluno")
    const divTipo = document.querySelector("#abc")
    const divAlunos = document.querySelector("#alunos")
    const tipos = {
        1: [["Participação em projetos de extensão ligados à matriz curricular.", "colaboracao"], ["Contribuição em projetos isolados cadastrados na PROEX.", "contribuicao"]], 
        2:[["Organização de eventos educacionais presenciais e remotos.", "coordenacao"], ["Engajamento em atividades de popularização científica.", "divulgacao"],["Colaboração em comissões de campanhas sociais e programas comunitários.", "participacao"],["Participação em Comissão organizadora de Campanhas ou programas sociais.", "organizacao"]],
        3: [["Capacitação de professores da rede pública.", "formacao"], ["Apoio em aulas de reforço escolar supervisionadas.", "auxilio"], ["Assessoria e consultoria para públicos-alvo específicos.", "orientacao"], ["Atendimento ao público em espaços culturais e científicos.", "interatividade"], ["Contribuição na produção de conteúdo sociocultural e científico-tecnológico.", "criacao"]]
    }
    selectModalidade.addEventListener("change",(e)=>{
        divTipo.innerHTML = ""
        let selectTipo = document.createElement("select")
        let divInputTipo = document.createElement("div")
        selectTipo.id ="atividade_tipo"
        selectTipo.name = "atividade[tipo]"
        selectTipo.classList.add("text-input")
        divInputTipo.append(selectTipo)
        if (e.target.value == ""){
            let op = document.createElement("option")
            op.innerText = "Tipo"
            selectTipo.appendChild(op)
            divTipo.append(divInputTipo)
        }else{
            if(e.target.value != 4){
                tipos[e.target.value].forEach(element => {
                    let op = document.createElement("option")
                    op.value = element[1]
                    op.innerText = element[0]
                    selectTipo.appendChild(op)
                });
                divTipo.append(divInputTipo)
            }else{
                let divInputTipo = document.createElement("div")
                let divInputHora = document.createElement("div")
                let inputTipo = document.createElement("input")
                let inputHora = document.createElement("input")
                inputTipo.id = "atividade_tipo"
                inputTipo.classList.add("text-input")
                inputTipo.placeholder = "Disciplina"
                inputTipo.name = "atividade[tipo]"
                inputHora.id = "atividade_carga_horaria"
                inputHora.placeholder = "Carga Horária"
                inputHora.classList.add("text-input")
                inputHora.name = "atividade[carga_horaria]"
                divInputTipo.append(inputTipo)
                divInputHora.append(inputHora)           
                divTipo.append(divInputTipo,divInputHora)
            }
        }
    })
    btnAluno.addEventListener("click",()=>{
        let inputAluno = document.createElement("input")
        inputAluno.name = "atividade[alunos][]"
        inputAluno.id = "atividade_alunos"
        inputAluno.multiple = "true"
        inputAluno.classList.add("text-input")
        inputAluno.placeholder = "Matricula do Aluno"
        divAlunos.appendChild(inputAluno)
        btnRmvAluno.style.display = "block"
    })
    btnRmvAluno.addEventListener("click",()=>{
        if (divAlunos.childElementCount > 1){
            divAlunos.removeChild(divAlunos.lastChild)
            btnRmvAluno.style.display = divAlunos.childElementCount == 1 ? "none":"block"
        }
        })

</script>